### ISSUE TITLE
Packaging & Testing

### ISSUE THREAD

**Issue by lermana** [jasperroebroek/sklearn-quantile#2]
Hey Jasper,

We communicated briefly on `skgarden`, where you pointed me here -- thanks for putting this together!

I had a couple of questions / comments / areas where I thought I could chip in, and was wondering what your thoughts were on the following:
- small, nit thing: I see `sklearn_quantile` as the package name in the [setup.py](https://github.com/jasperroebroek/sklearn-quantile/blob/master/setup.py#L23), but I see `sklearn-quantile` (which fits Python style guide) in PyPI. Am I just missing something because I'm tired (totally possible) or are you intended to have `sklearn_quantile` be the package name?
- I don't see instructions to install via `pip` on the README -- is that intentional (i.e. is there anything special going on in the `conda` install) or should the `pip` install work fine?
- it's great that you have some tests here -- would you be open to me adding more?

Best,

Abe

**Comment by jasperroebroek** [comment]
Hi Abe,

thanks for reaching out!

- I intended to use `sklearn-quantile` as the package name, but use sklearn_quantile as the name for importing in python. This seems to be quite common approach (see for example `flask-login` and `flask-sqlalchemy`). Not sure if this is the clearest approach, I am open to suggestions.
- Pip install should work fine
- I am always in favor of adding more tests if that improves stability. I currently don't have much time to invest in expanding them specifically. Again, I am open to suggestions!

Cheers,
Jasper
