### ISSUE TITLE
Class instance problem

### ISSUE THREAD

**Issue by doctordiaz** [jasperroebroek/sklearn-quantile#3]
Hi Jasper, thanks for the package, just trying to use it but always got same error, just this:

from sklearn_quantile import RandomForestQuantileRegressor
qrf = RandomForestQuantileRegressor()

gives error:
TypeError                                 Traceback (most recent call last)
[<ipython-input-20-e3602a1ff12d>](https://localhost:8080/#) in <cell line: 3>()
      1 from sklearn_quantile import RandomForestQuantileRegressor
      2 
----> 3 qrf = RandomForestQuantileRegressor()

sklearn_quantile/ensemble/quantile.pyx in sklearn_quantile.ensemble.quantile.RandomForestQuantileRegressor.__init__()

TypeError: __init__() missing 1 required positional argument: 'estimator'

I have not been able to debug it, could you please tell me how to use it please?

Best regards,

M

**Comment by jasperroebroek** [comment]
Hi @doctordiaz,

I am aware of this, it is caused by the changing of a parameter name in newer versions of scikit-learn. If you downgrade scikit-learn to any version below 1.2 it should work properly as in the documentation. I will try to find some time in the next week to resolve this issue. 

Cheers,
Jasper

**Comment by jasperroebroek** [comment]
In the meantime I fixed the issue and pushed the code to pypi. I can't seem to make the automatic build pass on conda, with strange errors appearing for python 3.11. Let me know if it works for you!

**Comment by jasperroebroek** [comment]
Okay, I managed to get it to work on conda too. Version 0.0.21 is available on both pypi and conda and should with python from 3.7.
