### ISSUE TITLE
multi output support

### ISSUE THREAD

**Issue by hualishiwo** [jasperroebroek/sklearn-quantile#4]
for extra trees regressor, do you support fit(x, y) while y is of size (n_sample, n_outputs) and n_outputs is not 1? I see in your source code, check_X_y uses multi_output=False, does it mean the multi_output is not supported yet?

**Comment by jasperroebroek** [comment]
This is indeed currently not possible. I have attempted on implementing this for the standard regressors, but this caused a severe performance penalty at prediction. For the sampling approach this should be relatively easy to implement however.

**Comment by jasperroebroek** [comment]
For now I close this issue, if there is a lot of interest in making this work I can take another look.
