### ISSUE TITLE
FutureWarning sklearn.utils.fixes.delayed

### ISSUE THREAD

**Issue by drdebivre** [jasperroebroek/sklearn-quantile#7]
Following warnings are generated when using .predict() on a RandomForestQuantileRegressor.
Is it just a matter of changing the import of the delayed function?

```
Lib\site-packages\sklearn\utils\deprecation.py:86: FutureWarning: Function delayed is deprecated; The function `delayed` has been moved from `sklearn.utils.fixes` to `sklearn.utils.parallel`. This import path will be removed in 1.5.
  warnings.warn(msg, category=FutureWarning)
Lib\site-packages\sklearn\utils\parallel.py:116: UserWarning: `sklearn.utils.parallel.delayed` should be used with `sklearn.utils.parallel.Parallel` to make it possible to propagate the scikit-learn configuration of the current thread to the joblib workers.
  warnings.warn(
```

**Comment by jasperroebroek** [comment]
Thanks for reporting, I will integrate this in the next release (v0.0.31).

**Comment by shadowkrusha** [comment]
@jasperroebroek Is there an ETA for the updated release? as this package will not work with scikit-learn >= 1.5.0

**Comment by jasperroebroek** [comment]
I have now uploaded v0.0.31 to PyPI, which should solve this issue. Let me know if the issue persists.
